# Generated by Django 6.0.3 on 2026-03-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone_1', models.CharField(blank=True, max_length=15)),
                ('telephone_2', models.CharField(blank=True, max_length=15)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
