# Generated by Django 6.0.3 on 2026-03-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('prix_ht', models.DecimalField(decimal_places=2, max_digits=15)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('stock_actuel', models.IntegerField(blank=True, default=0)),
                ('stock_mini_alerte', models.IntegerField(blank=True, default=5)),
            ],
        ),
    ]
